// Compiled shader for PC, Mac & Linux Standalone

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Shader Graphs/ColoredMaskedToon_b" {
    Properties{
    [NoScaleOffset] _SupraColor("ColorMapTexture", 2D) = "white" { }
     _Cor_1("Cor_1", Color) = (0.681042,0.000000,0.820755,0.000000)
     _Cor_2("Cor_2", Color) = (0.198113,0.057004,0.057004,1.000000)
     _Cor_3("Cor_3", Color) = (0.228375,0.113207,0.452830,0.000000)
     _Cor_4("Cor_4", Color) = (0.124156,0.773585,0.000000,1.000000)
     _Cor_5("Cor_5", Color) = (0.622642,0.313215,0.055803,0.000000)
     _Cor_6("Cor_6", Color) = (0.123354,0.415094,0.385411,0.000000)
    [NoScaleOffset]  _Shading_Gradient("Shading Gradient", 2D) = "white" { }
     _Gloss_size("Gloss Size", Float) = 10.000000
     _Fresnel_Angle("Fresnel Angle", Float) = -5.000000
     _Fresnel_Size("Fresnel Size", Float) = 0.100000
     _ShadowAttenFactor("ShadowAttenFactor", Range(0.000000,1.000000)) = 0.150000
     _ShadingBlacks("ShadingBlacks", Color) = (0.000000,0.000000,0.000000,0.000000)
     _ShadingWhites("ShadingWhites", Color) = (1.000000,1.000000,1.000000,0.000000)
    [HDR]  _Fresnel_Intensity("_Fresnel_Intensity", Color) = (1.000000,1.000000,1.000000,0.000000)
    [HDR]  _Gloss_intensity("_Gloss_intensity", Color) = (0.603774,0.603774,0.603774,0.000000)
    }
        SubShader{
         Tags { "QUEUE" = "Geometry+0" "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }


         // Stats for Vertex shader:
         //        d3d11: 16 math
         // Stats for Fragment shader:
         //        d3d11: 109 avg math (108..112), 2 texture, 1 branch
         Pass {
          Name "Pass"
          Tags { "QUEUE" = "Geometry+0" "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }
         //////////////////////////////////
         //                              //
         //      Compiled programs       //
         //                              //
         //////////////////////////////////
       //////////////////////////////////////////////////////
       Global Keywords : <none>
       Local Keywords : <none>
       --Hardware tier variant : Tier 1
       --Vertex shader for "d3d11" :
         // Stats: 16 math, 2 temp registers
         Uses vertex data channel "Vertex"
         Uses vertex data channel "Normal"
         Uses vertex data channel "TexCoord0"

         Constant Buffer "$Globals" (43376 bytes) on slot 0 {
           Matrix4x4 unity_MatrixVP at 21520
           Vector3 _WorldSpaceCameraPos at 20720
         }
         Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
           Matrix4x4 unity_ObjectToWorld at 0
           Matrix4x4 unity_WorldToObject at 64
         }

         Shader Disassembly :
         //
         // Generated by Microsoft (R) D3D Shader Disassembler
         //
         //
         // Input signature:
         //
         // Name                 Index   Mask Register SysValue  Format   Used
         // -------------------- ----- ------ -------- -------- ------- ------
         // POSITION                 0   xyz         0     NONE   float   xyz 
         // NORMAL                   0   xyz         1     NONE   float   xyz 
         // TANGENT                  0   xyzw        2     NONE   float       
         // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
         //
         //
         // Output signature:
         //
         // Name                 Index   Mask Register SysValue  Format   Used
         // -------------------- ----- ------ -------- -------- ------- ------
         // SV_POSITION              0   xyzw        0      POS   float   xyzw
         // TEXCOORD                 0   xyz         1     NONE   float   xyz 
         // TEXCOORD                 1   xyz         2     NONE   float   xyz 
         // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
         // TEXCOORD                 3   xyz         4     NONE   float   xyz 
         //
               vs_4_0
               dcl_constantbuffer CB0[1349], immediateIndexed
               dcl_constantbuffer CB1[7], immediateIndexed
               dcl_input v0.xyz
               dcl_input v1.xyz
               dcl_input v3.xyzw
               dcl_output_siv o0.xyzw, position
               dcl_output o1.xyz
               dcl_output o2.xyz
               dcl_output o3.xyzw
               dcl_output o4.xyz
               dcl_temps 2
            0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
            1 : mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
            2 : mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
            3 : add r0.xyz, r0.xyzx, cb1[3].xyzx
            4 : mul r1.xyzw, r0.yyyy, cb0[1346].xyzw
            5 : mad r1.xyzw, cb0[1345].xyzw, r0.xxxx, r1.xyzw
            6 : mad r1.xyzw, cb0[1347].xyzw, r0.zzzz, r1.xyzw
            7 : add o0.xyzw, r1.xyzw, cb0[1348].xyzw
            8 : mov o1.xyz, r0.xyzx
            9 : add o4.xyz, -r0.xyzx, cb0[1295].xyzx
           10 : dp3 r0.x, v1.xyzx, cb1[4].xyzx
           11 : dp3 r0.y, v1.xyzx, cb1[5].xyzx
           12 : dp3 r0.z, v1.xyzx, cb1[6].xyzx
           13 : dp3 r0.w, r0.xyzx, r0.xyzx
           14 : max r0.w, r0.w, l(0.000000)
           15 : rsq r0.w, r0.w
           16 : mul o2.xyz, r0.wwww, r0.xyzx
           17 : mov o3.xyzw, v3.xyzw
           18 : ret
                   // Approximately 0 instruction slots used


                   -- Hardware tier variant : Tier 1
                   --Fragment shader for "d3d11" :
                   // Stats: 108 math, 5 temp registers, 2 textures, 1 branches
                   Set 2D Texture "_MainLightShadowmapTexture" to slot 0
                   Set 2D Texture "_SupraColor" to slot 1
                   Set 2D Texture "_Shading_Gradient" to slot 2

                   Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                     Matrix4x4 _MainLightWorldToShadow[5] at 22272
                     Vector4 _MainLightPosition at 112
                     Vector4 _MainLightColor at 128
                     Vector4 _AdditionalLightsCount at 144
                     Vector4 _AdditionalLightsPosition[256] at 160
                     Vector4 _AdditionalLightsColor[256] at 4256
                     Vector4 _AdditionalLightsAttenuation[256] at 8352
                     Vector4 _AdditionalLightsSpotDir[256] at 12448
                     Vector4 _CascadeShadowSplitSpheres0 at 22592
                     Vector4 _CascadeShadowSplitSpheres1 at 22608
                     Vector4 _CascadeShadowSplitSpheres2 at 22624
                     Vector4 _CascadeShadowSplitSpheres3 at 22640
                     Vector4 _CascadeShadowSplitSphereRadii at 22656
                     Vector4 _MainLightShadowParams at 22736
                   }
                   Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                     Vector4 unity_LightData at 160
                     Vector4 unity_LightIndices[2] at 176
                   }
                   Constant Buffer "UnityPerMaterial" (176 bytes) on slot 2 {
                     Vector4 _Cor_1 at 0
                     Vector4 _Cor_2 at 16
                     Vector4 _Cor_3 at 32
                     Vector4 _Cor_4 at 48
                     Vector4 _Cor_5 at 64
                     Vector4 _Cor_6 at 80
                     Float _Gloss_size at 96
                     Float _Fresnel_Angle at 100
                     Float _Fresnel_Size at 104
                     Vector4 _ShadingBlacks at 112
                     Vector4 _ShadingWhites at 128
                     Vector4 _Fresnel_Intensity at 144
                     Vector4 _Gloss_intensity at 160
                   }

                   Shader Disassembly :
                   //
                   // Generated by Microsoft (R) D3D Shader Disassembler
                   //
                   //
                   // Input signature:
                   //
                   // Name                 Index   Mask Register SysValue  Format   Used
                   // -------------------- ----- ------ -------- -------- ------- ------
                   // SV_POSITION              0   xyzw        0      POS   float       
                   // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                   // TEXCOORD                 1   xyz         2     NONE   float   xyz 
                   // TEXCOORD                 2   xyzw        3     NONE   float   xy  
                   // TEXCOORD                 3   xyz         4     NONE   float   xyz 
                   //
                   //
                   // Output signature:
                   //
                   // Name                 Index   Mask Register SysValue  Format   Used
                   // -------------------- ----- ------ -------- -------- ------- ------
                   // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                   //
                         ps_4_0
                         dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                                                 { 0, 1.000000, 0, 0},
                                                 { 0, 0, 1.000000, 0},
                                                 { 0, 0, 0, 1.000000} }
                         dcl_constantbuffer CB0[1422], dynamicIndexed
                         dcl_constantbuffer CB1[13], dynamicIndexed
                         dcl_constantbuffer CB2[11], immediateIndexed
                         dcl_sampler s0, mode_comparison
                         dcl_sampler s1, mode_default
                         dcl_sampler s2, mode_default
                         dcl_resource_texture2d(float,float,float,float) t0
                         dcl_resource_texture2d(float,float,float,float) t1
                         dcl_resource_texture2d(float,float,float,float) t2
                         dcl_input_ps linear v1.xyz
                         dcl_input_ps linear v2.xyz
                         dcl_input_ps linear v3.xy
                         dcl_input_ps linear v4.xyz
                         dcl_output o0.xyzw
                         dcl_temps 5
                      0: dp3 r0.x, v2.xyzx, v2.xyzx
                      1 : sqrt r0.x, r0.x
                      2 : div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
                      3 : mul r0.xyz, r0.xxxx, v2.xyzx
                      4 : add r1.xyz, v1.xyzx, -cb0[1412].xyzx
                      5 : add r2.xyz, v1.xyzx, -cb0[1413].xyzx
                      6 : add r3.xyz, v1.xyzx, -cb0[1414].xyzx
                      7 : add r4.xyz, v1.xyzx, -cb0[1415].xyzx
                      8 : dp3 r1.x, r1.xyzx, r1.xyzx
                      9 : dp3 r1.y, r2.xyzx, r2.xyzx
                     10 : dp3 r1.z, r3.xyzx, r3.xyzx
                     11 : dp3 r1.w, r4.xyzx, r4.xyzx
                     12 : lt r1.xyzw, r1.xyzw, cb0[1416].xyzw
                     13 : and r2.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                     14 : movc r1.xyz, r1.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
                     15 : add r1.xyz, r1.xyzx, r2.yzwy
                     16 : max r2.yzw, r1.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
                     17 : dp4 r0.w, r2.xyzw, l(4.000000, 3.000000, 2.000000, 1.000000)
                     18 : add r0.w, -r0.w, l(4.000000)
                     19 : ftou r0.w, r0.w
                     20 : ishl r0.w, r0.w, l(2)
                     21 : mul r1.xyz, v1.yyyy, cb0[r0.w + 1393].xyzx
                     22 : mad r1.xyz, cb0[r0.w + 1392].xyzx, v1.xxxx, r1.xyzx
                     23 : mad r1.xyz, cb0[r0.w + 1394].xyzx, v1.zzzz, r1.xyzx
                     24 : add r1.xyz, r1.xyzx, cb0[r0.w + 1395].xyzx
                     25 : sample_c_lz r0.w, r1.xyxx, t0.xxxx, s0, r1.z
                     26 : add r1.x, -cb0[1421].x, l(1.000000)
                     27 : mad r0.w, r0.w, cb0[1421].x, r1.x
                     28 : ge r1.x, l(0.000000), r1.z
                     29 : ge r1.y, r1.z, l(1.000000)
                     30 : or r1.x, r1.y, r1.x
                     31 : movc r0.w, r1.x, l(1.000000), r0.w
                     32 : mul r0.w, r0.w, cb1[10].z
                     33 : dp3 r1.x, r0.xyzx, r0.xyzx
                     34 : rsq r1.x, r1.x
                     35 : mul r1.xyz, r0.xyzx, r1.xxxx
                     36 : min r1.w, cb0[9].x, cb1[10].y
                     37 : ftoi r1.w, r1.w
                     38 : mov r2.xyzw, l(0,0,0,0)
                     39 : loop
                     40 : ige r3.x, r2.w, r1.w
                     41 : breakc_nz r3.x
                     42 : and r3.x, r2.w, l(3)
                     43 : ushr r3.y, r2.w, l(2)
                     44 : dp4 r3.x, cb1[r3.y + 11].xyzw, icb[r3.x + 0].xyzw
                     45 : ftoi r3.x, r3.x
                     46 : mad r3.yzw, -v1.xxyz, cb0[r3.x + 10].wwww, cb0[r3.x + 10].xxyz
                     47 : dp3 r4.x, r3.yzwy, r3.yzwy
                     48 : max r4.x, r4.x, l(0.000061)
                     49 : rsq r4.y, r4.x
                     50 : mul r3.yzw, r3.yyzw, r4.yyyy
                     51 : div r4.y, l(1.000000, 1.000000, 1.000000, 1.000000), r4.x
                     52 : mul r4.x, r4.x, cb0[r3.x + 522].x
                     53 : mad r4.x, -r4.x, r4.x, l(1.000000)
                     54 : max r4.x, r4.x, l(0.000000)
                     55 : mul r4.x, r4.x, r4.x
                     56 : mul r4.x, r4.x, r4.y
                     57 : dp3 r4.y, cb0[r3.x + 778].xyzx, r3.yzwy
                     58 : mad_sat r4.y, r4.y, cb0[r3.x + 522].z, cb0[r3.x + 522].w
                     59 : mul r4.y, r4.y, r4.y
                     60 : mul r4.x, r4.y, r4.x
                     61 : mul r4.xyz, r4.xxxx, cb0[r3.x + 266].xyzx
                     62 : dp3_sat r3.x, r1.xyzx, r3.yzwy
                     63 : mad r2.xyz, r4.xyzx, r3.xxxx, r2.xyzx
                     64 : iadd r2.w, r2.w, l(1)
                     65 : endloop
                     66 : mad r2.xyz, cb0[8].xyzx, r0.wwww, r2.xyzx
                     67 : dp3 r0.w, v4.xyzx, v4.xyzx
                     68 : rsq r0.w, r0.w
                     69 : mul r3.xyz, r0.wwww, v4.xyzx
                     70 : mad r4.xyz, v4.xyzx, r0.wwww, cb0[7].xyzx
                     71 : dp3 r1.w, r1.xyzx, r4.xyzx
                     72 : log r1.w, r1.w
                     73 : mul r1.w, r1.w, cb2[6].x
                     74 : exp r1.w, r1.w
                     75 : ge r1.w, r1.w, l(0.100000)
                     76 : and r1.w, r1.w, l(0x3f800000)
                     77 : dp3_sat r2.w, r1.xyzx, r3.xyzx
                     78 : add r2.w, -r2.w, l(1.000000)
                     79 : log r2.w, r2.w
                     80 : mul r2.w, r2.w, cb2[6].z
                     81 : exp r2.w, r2.w
                     82 : mad r1.xyz, v4.xyzx, r0.wwww, -r1.xyzx
                     83 : dp3 r0.w, r1.xyzx, r1.xyzx
                     84 : rsq r0.w, r0.w
                     85 : mul r1.xyz, r0.wwww, r1.xyzx
                     86 : dp3 r0.w, cb0[7].xyzx, r1.xyzx
                     87 : add r0.w, r0.w, l(1.000000)
                     88 : add r1.x, cb2[6].y, l(-1.000000)
                     89 : mul r0.w, r0.w, r1.x
                     90 : mad r0.w, r0.w, l(0.500000), l(1.000000)
                     91 : mul r0.w, r0.w, r2.w
                     92 : ge r0.w, r0.w, l(0.100000)
                     93 : and r0.w, r0.w, l(0x3f800000)
                     94 : dp3 r0.x, r0.xyzx, cb0[7].xyzx
                     95 : add r0.x, r0.x, l(1.000000)
                     96 : mad r0.x, r0.x, l(0.490000), l(0.010000)
                     97 : mov r0.y, l(1.000000)
                     98 : sample r3.xyzw, r0.xyxx, t2.xyzw, s2
                     99 : max r0.xyz, r3.xyzx, l(0.010000, 0.010000, 0.010000, 0.000000)
                    100 : mad r0.xyz, r0.wwww, cb2[9].xyzx, r0.xyzx
                    101 : mad r0.xyz, r1.wwww, cb2[10].xyzx, r0.xyzx
                    102 : mul r0.xyz, r0.xyzx, r2.xyzx
                    103 : max r1.xyz, cb2[7].xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
                    104 : mad r0.xyz, cb2[8].xyzx, r0.xyzx, r1.xyzx
                    105 : sample r1.xyzw, v3.xyxx, t1.xyzw, s1
                    106 : add r2.xy, -r1.zyzz, r1.yzyy
                    107 : add_sat r2.xy, -r1.xxxx, r2.xyxx
                    108 : add r3.xyz, -cb2[0].xyzx, cb2[1].xyzx
                    109 : mad r2.xzw, r2.xxxx, r3.xxyz, cb2[0].xxyz
                    110 : add r3.xyz, -r2.xzwx, cb2[2].xyzx
                    111 : mad r2.xyz, r2.yyyy, r3.xyzx, r2.xzwx
                    112 : mul r1.xyz, r1.yzzy, r1.xyxx
                    113 : round_z r1.xyz, r1.xyzx
                    114 : add r3.xyz, -r2.xyzx, cb2[3].xyzx
                    115 : mad r2.xyz, r1.xxxx, r3.xyzx, r2.xyzx
                    116 : add r3.xyz, -r2.xyzx, cb2[4].xyzx
                    117 : mad r1.xyw, r1.yyyy, r3.xyxz, r2.xyxz
                    118 : add r2.xyz, -r1.xywx, cb2[5].xyzx
                    119 : mad r1.xyz, r1.zzzz, r2.xyzx, r1.xywx
                    120 : mul o0.xyz, r0.xyzx, r1.xyzx
                    121 : mov o0.w, l(1.000000)
                    122 : ret
                             // Approximately 0 instruction slots used


                             //////////////////////////////////////////////////////
                             Global Keywords : DIRLIGHTMAP_COMBINED
                             Local Keywords : <none>
                             --Hardware tier variant : Tier 1
                             --Vertex shader for "d3d11" :
                             // Stats: 16 math, 2 temp registers
                             Uses vertex data channel "Vertex"
                             Uses vertex data channel "Normal"
                             Uses vertex data channel "TexCoord0"

                             Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                               Matrix4x4 unity_MatrixVP at 21520
                               Vector3 _WorldSpaceCameraPos at 20720
                             }
                             Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                               Matrix4x4 unity_ObjectToWorld at 0
                               Matrix4x4 unity_WorldToObject at 64
                             }

                             Shader Disassembly :
                             //
                             // Generated by Microsoft (R) D3D Shader Disassembler
                             //
                             //
                             // Input signature:
                             //
                             // Name                 Index   Mask Register SysValue  Format   Used
                             // -------------------- ----- ------ -------- -------- ------- ------
                             // POSITION                 0   xyz         0     NONE   float   xyz 
                             // NORMAL                   0   xyz         1     NONE   float   xyz 
                             // TANGENT                  0   xyzw        2     NONE   float       
                             // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
                             //
                             //
                             // Output signature:
                             //
                             // Name                 Index   Mask Register SysValue  Format   Used
                             // -------------------- ----- ------ -------- -------- ------- ------
                             // SV_POSITION              0   xyzw        0      POS   float   xyzw
                             // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                             // TEXCOORD                 1   xyz         2     NONE   float   xyz 
                             // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
                             // TEXCOORD                 3   xyz         4     NONE   float   xyz 
                             //
                                   vs_4_0
                                   dcl_constantbuffer CB0[1349], immediateIndexed
                                   dcl_constantbuffer CB1[7], immediateIndexed
                                   dcl_input v0.xyz
                                   dcl_input v1.xyz
                                   dcl_input v3.xyzw
                                   dcl_output_siv o0.xyzw, position
                                   dcl_output o1.xyz
                                   dcl_output o2.xyz
                                   dcl_output o3.xyzw
                                   dcl_output o4.xyz
                                   dcl_temps 2
                                0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
                                1 : mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
                                2 : mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
                                3 : add r0.xyz, r0.xyzx, cb1[3].xyzx
                                4 : mul r1.xyzw, r0.yyyy, cb0[1346].xyzw
                                5 : mad r1.xyzw, cb0[1345].xyzw, r0.xxxx, r1.xyzw
                                6 : mad r1.xyzw, cb0[1347].xyzw, r0.zzzz, r1.xyzw
                                7 : add o0.xyzw, r1.xyzw, cb0[1348].xyzw
                                8 : mov o1.xyz, r0.xyzx
                                9 : add o4.xyz, -r0.xyzx, cb0[1295].xyzx
                               10 : dp3 r0.x, v1.xyzx, cb1[4].xyzx
                               11 : dp3 r0.y, v1.xyzx, cb1[5].xyzx
                               12 : dp3 r0.z, v1.xyzx, cb1[6].xyzx
                               13 : dp3 r0.w, r0.xyzx, r0.xyzx
                               14 : max r0.w, r0.w, l(0.000000)
                               15 : rsq r0.w, r0.w
                               16 : mul o2.xyz, r0.wwww, r0.xyzx
                               17 : mov o3.xyzw, v3.xyzw
                               18 : ret
                                       // Approximately 0 instruction slots used


                                       -- Hardware tier variant : Tier 1
                                       --Fragment shader for "d3d11" :
                                       // Stats: 108 math, 5 temp registers, 2 textures, 1 branches
                                       Set 2D Texture "_MainLightShadowmapTexture" to slot 0
                                       Set 2D Texture "_SupraColor" to slot 1
                                       Set 2D Texture "_Shading_Gradient" to slot 2

                                       Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                                         Matrix4x4 _MainLightWorldToShadow[5] at 22272
                                         Vector4 _MainLightPosition at 112
                                         Vector4 _MainLightColor at 128
                                         Vector4 _AdditionalLightsCount at 144
                                         Vector4 _AdditionalLightsPosition[256] at 160
                                         Vector4 _AdditionalLightsColor[256] at 4256
                                         Vector4 _AdditionalLightsAttenuation[256] at 8352
                                         Vector4 _AdditionalLightsSpotDir[256] at 12448
                                         Vector4 _CascadeShadowSplitSpheres0 at 22592
                                         Vector4 _CascadeShadowSplitSpheres1 at 22608
                                         Vector4 _CascadeShadowSplitSpheres2 at 22624
                                         Vector4 _CascadeShadowSplitSpheres3 at 22640
                                         Vector4 _CascadeShadowSplitSphereRadii at 22656
                                         Vector4 _MainLightShadowParams at 22736
                                       }
                                       Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                                         Vector4 unity_LightData at 160
                                         Vector4 unity_LightIndices[2] at 176
                                       }
                                       Constant Buffer "UnityPerMaterial" (176 bytes) on slot 2 {
                                         Vector4 _Cor_1 at 0
                                         Vector4 _Cor_2 at 16
                                         Vector4 _Cor_3 at 32
                                         Vector4 _Cor_4 at 48
                                         Vector4 _Cor_5 at 64
                                         Vector4 _Cor_6 at 80
                                         Float _Gloss_size at 96
                                         Float _Fresnel_Angle at 100
                                         Float _Fresnel_Size at 104
                                         Vector4 _ShadingBlacks at 112
                                         Vector4 _ShadingWhites at 128
                                         Vector4 _Fresnel_Intensity at 144
                                         Vector4 _Gloss_intensity at 160
                                       }

                                       Shader Disassembly :
                                       //
                                       // Generated by Microsoft (R) D3D Shader Disassembler
                                       //
                                       //
                                       // Input signature:
                                       //
                                       // Name                 Index   Mask Register SysValue  Format   Used
                                       // -------------------- ----- ------ -------- -------- ------- ------
                                       // SV_POSITION              0   xyzw        0      POS   float       
                                       // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                                       // TEXCOORD                 1   xyz         2     NONE   float   xyz 
                                       // TEXCOORD                 2   xyzw        3     NONE   float   xy  
                                       // TEXCOORD                 3   xyz         4     NONE   float   xyz 
                                       //
                                       //
                                       // Output signature:
                                       //
                                       // Name                 Index   Mask Register SysValue  Format   Used
                                       // -------------------- ----- ------ -------- -------- ------- ------
                                       // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                                       //
                                             ps_4_0
                                             dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                                                                     { 0, 1.000000, 0, 0},
                                                                     { 0, 0, 1.000000, 0},
                                                                     { 0, 0, 0, 1.000000} }
                                             dcl_constantbuffer CB0[1422], dynamicIndexed
                                             dcl_constantbuffer CB1[13], dynamicIndexed
                                             dcl_constantbuffer CB2[11], immediateIndexed
                                             dcl_sampler s0, mode_comparison
                                             dcl_sampler s1, mode_default
                                             dcl_sampler s2, mode_default
                                             dcl_resource_texture2d(float,float,float,float) t0
                                             dcl_resource_texture2d(float,float,float,float) t1
                                             dcl_resource_texture2d(float,float,float,float) t2
                                             dcl_input_ps linear v1.xyz
                                             dcl_input_ps linear v2.xyz
                                             dcl_input_ps linear v3.xy
                                             dcl_input_ps linear v4.xyz
                                             dcl_output o0.xyzw
                                             dcl_temps 5
                                          0: dp3 r0.x, v2.xyzx, v2.xyzx
                                          1 : sqrt r0.x, r0.x
                                          2 : div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
                                          3 : mul r0.xyz, r0.xxxx, v2.xyzx
                                          4 : add r1.xyz, v1.xyzx, -cb0[1412].xyzx
                                          5 : add r2.xyz, v1.xyzx, -cb0[1413].xyzx
                                          6 : add r3.xyz, v1.xyzx, -cb0[1414].xyzx
                                          7 : add r4.xyz, v1.xyzx, -cb0[1415].xyzx
                                          8 : dp3 r1.x, r1.xyzx, r1.xyzx
                                          9 : dp3 r1.y, r2.xyzx, r2.xyzx
                                         10 : dp3 r1.z, r3.xyzx, r3.xyzx
                                         11 : dp3 r1.w, r4.xyzx, r4.xyzx
                                         12 : lt r1.xyzw, r1.xyzw, cb0[1416].xyzw
                                         13 : and r2.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                                         14 : movc r1.xyz, r1.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
                                         15 : add r1.xyz, r1.xyzx, r2.yzwy
                                         16 : max r2.yzw, r1.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
                                         17 : dp4 r0.w, r2.xyzw, l(4.000000, 3.000000, 2.000000, 1.000000)
                                         18 : add r0.w, -r0.w, l(4.000000)
                                         19 : ftou r0.w, r0.w
                                         20 : ishl r0.w, r0.w, l(2)
                                         21 : mul r1.xyz, v1.yyyy, cb0[r0.w + 1393].xyzx
                                         22 : mad r1.xyz, cb0[r0.w + 1392].xyzx, v1.xxxx, r1.xyzx
                                         23 : mad r1.xyz, cb0[r0.w + 1394].xyzx, v1.zzzz, r1.xyzx
                                         24 : add r1.xyz, r1.xyzx, cb0[r0.w + 1395].xyzx
                                         25 : sample_c_lz r0.w, r1.xyxx, t0.xxxx, s0, r1.z
                                         26 : add r1.x, -cb0[1421].x, l(1.000000)
                                         27 : mad r0.w, r0.w, cb0[1421].x, r1.x
                                         28 : ge r1.x, l(0.000000), r1.z
                                         29 : ge r1.y, r1.z, l(1.000000)
                                         30 : or r1.x, r1.y, r1.x
                                         31 : movc r0.w, r1.x, l(1.000000), r0.w
                                         32 : mul r0.w, r0.w, cb1[10].z
                                         33 : dp3 r1.x, r0.xyzx, r0.xyzx
                                         34 : rsq r1.x, r1.x
                                         35 : mul r1.xyz, r0.xyzx, r1.xxxx
                                         36 : min r1.w, cb0[9].x, cb1[10].y
                                         37 : ftoi r1.w, r1.w
                                         38 : mov r2.xyzw, l(0,0,0,0)
                                         39 : loop
                                         40 : ige r3.x, r2.w, r1.w
                                         41 : breakc_nz r3.x
                                         42 : and r3.x, r2.w, l(3)
                                         43 : ushr r3.y, r2.w, l(2)
                                         44 : dp4 r3.x, cb1[r3.y + 11].xyzw, icb[r3.x + 0].xyzw
                                         45 : ftoi r3.x, r3.x
                                         46 : mad r3.yzw, -v1.xxyz, cb0[r3.x + 10].wwww, cb0[r3.x + 10].xxyz
                                         47 : dp3 r4.x, r3.yzwy, r3.yzwy
                                         48 : max r4.x, r4.x, l(0.000061)
                                         49 : rsq r4.y, r4.x
                                         50 : mul r3.yzw, r3.yyzw, r4.yyyy
                                         51 : div r4.y, l(1.000000, 1.000000, 1.000000, 1.000000), r4.x
                                         52 : mul r4.x, r4.x, cb0[r3.x + 522].x
                                         53 : mad r4.x, -r4.x, r4.x, l(1.000000)
                                         54 : max r4.x, r4.x, l(0.000000)
                                         55 : mul r4.x, r4.x, r4.x
                                         56 : mul r4.x, r4.x, r4.y
                                         57 : dp3 r4.y, cb0[r3.x + 778].xyzx, r3.yzwy
                                         58 : mad_sat r4.y, r4.y, cb0[r3.x + 522].z, cb0[r3.x + 522].w
                                         59 : mul r4.y, r4.y, r4.y
                                         60 : mul r4.x, r4.y, r4.x
                                         61 : mul r4.xyz, r4.xxxx, cb0[r3.x + 266].xyzx
                                         62 : dp3_sat r3.x, r1.xyzx, r3.yzwy
                                         63 : mad r2.xyz, r4.xyzx, r3.xxxx, r2.xyzx
                                         64 : iadd r2.w, r2.w, l(1)
                                         65 : endloop
                                         66 : mad r2.xyz, cb0[8].xyzx, r0.wwww, r2.xyzx
                                         67 : dp3 r0.w, v4.xyzx, v4.xyzx
                                         68 : rsq r0.w, r0.w
                                         69 : mul r3.xyz, r0.wwww, v4.xyzx
                                         70 : mad r4.xyz, v4.xyzx, r0.wwww, cb0[7].xyzx
                                         71 : dp3 r1.w, r1.xyzx, r4.xyzx
                                         72 : log r1.w, r1.w
                                         73 : mul r1.w, r1.w, cb2[6].x
                                         74 : exp r1.w, r1.w
                                         75 : ge r1.w, r1.w, l(0.100000)
                                         76 : and r1.w, r1.w, l(0x3f800000)
                                         77 : dp3_sat r2.w, r1.xyzx, r3.xyzx
                                         78 : add r2.w, -r2.w, l(1.000000)
                                         79 : log r2.w, r2.w
                                         80 : mul r2.w, r2.w, cb2[6].z
                                         81 : exp r2.w, r2.w
                                         82 : mad r1.xyz, v4.xyzx, r0.wwww, -r1.xyzx
                                         83 : dp3 r0.w, r1.xyzx, r1.xyzx
                                         84 : rsq r0.w, r0.w
                                         85 : mul r1.xyz, r0.wwww, r1.xyzx
                                         86 : dp3 r0.w, cb0[7].xyzx, r1.xyzx
                                         87 : add r0.w, r0.w, l(1.000000)
                                         88 : add r1.x, cb2[6].y, l(-1.000000)
                                         89 : mul r0.w, r0.w, r1.x
                                         90 : mad r0.w, r0.w, l(0.500000), l(1.000000)
                                         91 : mul r0.w, r0.w, r2.w
                                         92 : ge r0.w, r0.w, l(0.100000)
                                         93 : and r0.w, r0.w, l(0x3f800000)
                                         94 : dp3 r0.x, r0.xyzx, cb0[7].xyzx
                                         95 : add r0.x, r0.x, l(1.000000)
                                         96 : mad r0.x, r0.x, l(0.490000), l(0.010000)
                                         97 : mov r0.y, l(1.000000)
                                         98 : sample r3.xyzw, r0.xyxx, t2.xyzw, s2
                                         99 : max r0.xyz, r3.xyzx, l(0.010000, 0.010000, 0.010000, 0.000000)
                                        100 : mad r0.xyz, r0.wwww, cb2[9].xyzx, r0.xyzx
                                        101 : mad r0.xyz, r1.wwww, cb2[10].xyzx, r0.xyzx
                                        102 : mul r0.xyz, r0.xyzx, r2.xyzx
                                        103 : max r1.xyz, cb2[7].xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
                                        104 : mad r0.xyz, cb2[8].xyzx, r0.xyzx, r1.xyzx
                                        105 : sample r1.xyzw, v3.xyxx, t1.xyzw, s1
                                        106 : add r2.xy, -r1.zyzz, r1.yzyy
                                        107 : add_sat r2.xy, -r1.xxxx, r2.xyxx
                                        108 : add r3.xyz, -cb2[0].xyzx, cb2[1].xyzx
                                        109 : mad r2.xzw, r2.xxxx, r3.xxyz, cb2[0].xxyz
                                        110 : add r3.xyz, -r2.xzwx, cb2[2].xyzx
                                        111 : mad r2.xyz, r2.yyyy, r3.xyzx, r2.xzwx
                                        112 : mul r1.xyz, r1.yzzy, r1.xyxx
                                        113 : round_z r1.xyz, r1.xyzx
                                        114 : add r3.xyz, -r2.xyzx, cb2[3].xyzx
                                        115 : mad r2.xyz, r1.xxxx, r3.xyzx, r2.xyzx
                                        116 : add r3.xyz, -r2.xyzx, cb2[4].xyzx
                                        117 : mad r1.xyw, r1.yyyy, r3.xyxz, r2.xyxz
                                        118 : add r2.xyz, -r1.xywx, cb2[5].xyzx
                                        119 : mad r1.xyz, r1.zzzz, r2.xyzx, r1.xywx
                                        120 : mul o0.xyz, r0.xyzx, r1.xyzx
                                        121 : mov o0.w, l(1.000000)
                                        122 : ret
                                                 // Approximately 0 instruction slots used


                                                 //////////////////////////////////////////////////////
                                                 Global Keywords : DIRLIGHTMAP_COMBINED LIGHTMAP_ON
                                                 Local Keywords : <none>
                                                 --Hardware tier variant : Tier 1
                                                 --Vertex shader for "d3d11" :
                                                 // Stats: 16 math, 2 temp registers
                                                 Uses vertex data channel "Vertex"
                                                 Uses vertex data channel "Normal"
                                                 Uses vertex data channel "TexCoord0"

                                                 Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                                                   Matrix4x4 unity_MatrixVP at 21520
                                                   Vector3 _WorldSpaceCameraPos at 20720
                                                 }
                                                 Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                                                   Matrix4x4 unity_ObjectToWorld at 0
                                                   Matrix4x4 unity_WorldToObject at 64
                                                 }

                                                 Shader Disassembly :
                                                 //
                                                 // Generated by Microsoft (R) D3D Shader Disassembler
                                                 //
                                                 //
                                                 // Input signature:
                                                 //
                                                 // Name                 Index   Mask Register SysValue  Format   Used
                                                 // -------------------- ----- ------ -------- -------- ------- ------
                                                 // POSITION                 0   xyz         0     NONE   float   xyz 
                                                 // NORMAL                   0   xyz         1     NONE   float   xyz 
                                                 // TANGENT                  0   xyzw        2     NONE   float       
                                                 // TEXCOORD                 0   xyzw        3     NONE   float   xyzw
                                                 //
                                                 //
                                                 // Output signature:
                                                 //
                                                 // Name                 Index   Mask Register SysValue  Format   Used
                                                 // -------------------- ----- ------ -------- -------- ------- ------
                                                 // SV_POSITION              0   xyzw        0      POS   float   xyzw
                                                 // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                                                 // TEXCOORD                 1   xyz         2     NONE   float   xyz 
                                                 // TEXCOORD                 2   xyzw        3     NONE   float   xyzw
                                                 // TEXCOORD                 3   xyz         4     NONE   float   xyz 
                                                 //
                                                       vs_4_0
                                                       dcl_constantbuffer CB0[1349], immediateIndexed
                                                       dcl_constantbuffer CB1[7], immediateIndexed
                                                       dcl_input v0.xyz
                                                       dcl_input v1.xyz
                                                       dcl_input v3.xyzw
                                                       dcl_output_siv o0.xyzw, position
                                                       dcl_output o1.xyz
                                                       dcl_output o2.xyz
                                                       dcl_output o3.xyzw
                                                       dcl_output o4.xyz
                                                       dcl_temps 2
                                                    0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
                                                    1 : mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
                                                    2 : mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
                                                    3 : add r0.xyz, r0.xyzx, cb1[3].xyzx
                                                    4 : mul r1.xyzw, r0.yyyy, cb0[1346].xyzw
                                                    5 : mad r1.xyzw, cb0[1345].xyzw, r0.xxxx, r1.xyzw
                                                    6 : mad r1.xyzw, cb0[1347].xyzw, r0.zzzz, r1.xyzw
                                                    7 : add o0.xyzw, r1.xyzw, cb0[1348].xyzw
                                                    8 : mov o1.xyz, r0.xyzx
                                                    9 : add o4.xyz, -r0.xyzx, cb0[1295].xyzx
                                                   10 : dp3 r0.x, v1.xyzx, cb1[4].xyzx
                                                   11 : dp3 r0.y, v1.xyzx, cb1[5].xyzx
                                                   12 : dp3 r0.z, v1.xyzx, cb1[6].xyzx
                                                   13 : dp3 r0.w, r0.xyzx, r0.xyzx
                                                   14 : max r0.w, r0.w, l(0.000000)
                                                   15 : rsq r0.w, r0.w
                                                   16 : mul o2.xyz, r0.wwww, r0.xyzx
                                                   17 : mov o3.xyzw, v3.xyzw
                                                   18 : ret
                                                           // Approximately 0 instruction slots used


                                                           -- Hardware tier variant : Tier 1
                                                           --Fragment shader for "d3d11" :
                                                           // Stats: 112 math, 5 temp registers, 2 textures, 1 branches
                                                           Set 2D Texture "_MainLightShadowmapTexture" to slot 0
                                                           Set 2D Texture "_SupraColor" to slot 1
                                                           Set 2D Texture "_Shading_Gradient" to slot 2

                                                           Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                                                             Matrix4x4 _MainLightWorldToShadow[5] at 22272
                                                             Vector4 _MainLightPosition at 112
                                                             Vector4 _MainLightColor at 128
                                                             Vector4 _AdditionalLightsCount at 144
                                                             Vector4 _AdditionalLightsPosition[256] at 160
                                                             Vector4 _AdditionalLightsColor[256] at 4256
                                                             Vector4 _AdditionalLightsAttenuation[256] at 8352
                                                             Vector4 _AdditionalLightsSpotDir[256] at 12448
                                                             Vector4 _AdditionalLightsOcclusionProbes[256] at 16544
                                                             Vector4 _CascadeShadowSplitSpheres0 at 22592
                                                             Vector4 _CascadeShadowSplitSpheres1 at 22608
                                                             Vector4 _CascadeShadowSplitSpheres2 at 22624
                                                             Vector4 _CascadeShadowSplitSpheres3 at 22640
                                                             Vector4 _CascadeShadowSplitSphereRadii at 22656
                                                             Vector4 _MainLightShadowParams at 22736
                                                           }
                                                           Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                                                             Vector4 unity_LightData at 160
                                                             Vector4 unity_LightIndices[2] at 176
                                                             Vector4 unity_ProbesOcclusion at 208
                                                           }
                                                           Constant Buffer "UnityPerMaterial" (176 bytes) on slot 2 {
                                                             Vector4 _Cor_1 at 0
                                                             Vector4 _Cor_2 at 16
                                                             Vector4 _Cor_3 at 32
                                                             Vector4 _Cor_4 at 48
                                                             Vector4 _Cor_5 at 64
                                                             Vector4 _Cor_6 at 80
                                                             Float _Gloss_size at 96
                                                             Float _Fresnel_Angle at 100
                                                             Float _Fresnel_Size at 104
                                                             Vector4 _ShadingBlacks at 112
                                                             Vector4 _ShadingWhites at 128
                                                             Vector4 _Fresnel_Intensity at 144
                                                             Vector4 _Gloss_intensity at 160
                                                           }

                                                           Shader Disassembly :
                                                           //
                                                           // Generated by Microsoft (R) D3D Shader Disassembler
                                                           //
                                                           //
                                                           // Input signature:
                                                           //
                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                           // SV_POSITION              0   xyzw        0      POS   float       
                                                           // TEXCOORD                 0   xyz         1     NONE   float   xyz 
                                                           // TEXCOORD                 1   xyz         2     NONE   float   xyz 
                                                           // TEXCOORD                 2   xyzw        3     NONE   float   xy  
                                                           // TEXCOORD                 3   xyz         4     NONE   float   xyz 
                                                           //
                                                           //
                                                           // Output signature:
                                                           //
                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                           // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                                                           //
                                                                 ps_4_0
                                                                 dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                                                                                         { 0, 1.000000, 0, 0},
                                                                                         { 0, 0, 1.000000, 0},
                                                                                         { 0, 0, 0, 1.000000} }
                                                                 dcl_constantbuffer CB0[1422], dynamicIndexed
                                                                 dcl_constantbuffer CB1[14], dynamicIndexed
                                                                 dcl_constantbuffer CB2[11], immediateIndexed
                                                                 dcl_sampler s0, mode_comparison
                                                                 dcl_sampler s1, mode_default
                                                                 dcl_sampler s2, mode_default
                                                                 dcl_resource_texture2d(float,float,float,float) t0
                                                                 dcl_resource_texture2d(float,float,float,float) t1
                                                                 dcl_resource_texture2d(float,float,float,float) t2
                                                                 dcl_input_ps linear v1.xyz
                                                                 dcl_input_ps linear v2.xyz
                                                                 dcl_input_ps linear v3.xy
                                                                 dcl_input_ps linear v4.xyz
                                                                 dcl_output o0.xyzw
                                                                 dcl_temps 5
                                                              0: dp3 r0.x, v2.xyzx, v2.xyzx
                                                              1 : sqrt r0.x, r0.x
                                                              2 : div r0.x, l(1.000000, 1.000000, 1.000000, 1.000000), r0.x
                                                              3 : mul r0.xyz, r0.xxxx, v2.xyzx
                                                              4 : add r1.xyz, v1.xyzx, -cb0[1412].xyzx
                                                              5 : add r2.xyz, v1.xyzx, -cb0[1413].xyzx
                                                              6 : add r3.xyz, v1.xyzx, -cb0[1414].xyzx
                                                              7 : add r4.xyz, v1.xyzx, -cb0[1415].xyzx
                                                              8 : dp3 r1.x, r1.xyzx, r1.xyzx
                                                              9 : dp3 r1.y, r2.xyzx, r2.xyzx
                                                             10 : dp3 r1.z, r3.xyzx, r3.xyzx
                                                             11 : dp3 r1.w, r4.xyzx, r4.xyzx
                                                             12 : lt r1.xyzw, r1.xyzw, cb0[1416].xyzw
                                                             13 : and r2.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                                                             14 : movc r1.xyz, r1.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
                                                             15 : add r1.xyz, r1.xyzx, r2.yzwy
                                                             16 : max r2.yzw, r1.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
                                                             17 : dp4 r0.w, r2.xyzw, l(4.000000, 3.000000, 2.000000, 1.000000)
                                                             18 : add r0.w, -r0.w, l(4.000000)
                                                             19 : ftou r0.w, r0.w
                                                             20 : ishl r0.w, r0.w, l(2)
                                                             21 : mul r1.xyz, v1.yyyy, cb0[r0.w + 1393].xyzx
                                                             22 : mad r1.xyz, cb0[r0.w + 1392].xyzx, v1.xxxx, r1.xyzx
                                                             23 : mad r1.xyz, cb0[r0.w + 1394].xyzx, v1.zzzz, r1.xyzx
                                                             24 : add r1.xyz, r1.xyzx, cb0[r0.w + 1395].xyzx
                                                             25 : mul r0.w, cb1[10].z, cb1[13].x
                                                             26 : sample_c_lz r1.x, r1.xyxx, t0.xxxx, s0, r1.z
                                                             27 : add r1.y, -cb0[1421].x, l(1.000000)
                                                             28 : mad r1.x, r1.x, cb0[1421].x, r1.y
                                                             29 : ge r1.y, l(0.000000), r1.z
                                                             30 : ge r1.z, r1.z, l(1.000000)
                                                             31 : or r1.y, r1.z, r1.y
                                                             32 : movc r1.x, r1.y, l(1.000000), r1.x
                                                             33 : mul r0.w, r0.w, r1.x
                                                             34 : dp3 r1.x, r0.xyzx, r0.xyzx
                                                             35 : rsq r1.x, r1.x
                                                             36 : mul r1.xyz, r0.xyzx, r1.xxxx
                                                             37 : min r1.w, cb0[9].x, cb1[10].y
                                                             38 : ftoi r1.w, r1.w
                                                             39 : mov r2.xyzw, l(0,0,0,0)
                                                             40 : loop
                                                             41 : ige r3.x, r2.w, r1.w
                                                             42 : breakc_nz r3.x
                                                             43 : and r3.x, r2.w, l(3)
                                                             44 : ushr r3.y, r2.w, l(2)
                                                             45 : dp4 r3.x, cb1[r3.y + 11].xyzw, icb[r3.x + 0].xyzw
                                                             46 : ftoi r3.x, r3.x
                                                             47 : mad r3.yzw, -v1.xxyz, cb0[r3.x + 10].wwww, cb0[r3.x + 10].xxyz
                                                             48 : dp3 r4.x, r3.yzwy, r3.yzwy
                                                             49 : max r4.x, r4.x, l(0.000061)
                                                             50 : rsq r4.y, r4.x
                                                             51 : mul r3.yzw, r3.yyzw, r4.yyyy
                                                             52 : div r4.y, l(1.000000, 1.000000, 1.000000, 1.000000), r4.x
                                                             53 : mul r4.x, r4.x, cb0[r3.x + 522].x
                                                             54 : mad r4.x, -r4.x, r4.x, l(1.000000)
                                                             55 : max r4.x, r4.x, l(0.000000)
                                                             56 : mul r4.x, r4.x, r4.x
                                                             57 : mul r4.x, r4.x, r4.y
                                                             58 : dp3 r4.y, cb0[r3.x + 778].xyzx, r3.yzwy
                                                             59 : mad_sat r4.y, r4.y, cb0[r3.x + 522].z, cb0[r3.x + 522].w
                                                             60 : mul r4.y, r4.y, r4.y
                                                             61 : mul r4.x, r4.y, r4.x
                                                             62 : ftoi r4.y, cb0[r3.x + 1034].x
                                                             63 : dp4 r4.y, cb1[13].xyzw, icb[r4.y + 0].xyzw
                                                             64 : max r4.y, r4.y, cb0[r3.x + 1034].y
                                                             65 : mul r4.x, r4.y, r4.x
                                                             66 : mul r4.xyz, r4.xxxx, cb0[r3.x + 266].xyzx
                                                             67 : dp3_sat r3.x, r1.xyzx, r3.yzwy
                                                             68 : mad r2.xyz, r4.xyzx, r3.xxxx, r2.xyzx
                                                             69 : iadd r2.w, r2.w, l(1)
                                                             70 : endloop
                                                             71 : mad r2.xyz, cb0[8].xyzx, r0.wwww, r2.xyzx
                                                             72 : dp3 r0.w, v4.xyzx, v4.xyzx
                                                             73 : rsq r0.w, r0.w
                                                             74 : mul r3.xyz, r0.wwww, v4.xyzx
                                                             75 : mad r4.xyz, v4.xyzx, r0.wwww, cb0[7].xyzx
                                                             76 : dp3 r1.w, r1.xyzx, r4.xyzx
                                                             77 : log r1.w, r1.w
                                                             78 : mul r1.w, r1.w, cb2[6].x
                                                             79 : exp r1.w, r1.w
                                                             80 : ge r1.w, r1.w, l(0.100000)
                                                             81 : and r1.w, r1.w, l(0x3f800000)
                                                             82 : dp3_sat r2.w, r1.xyzx, r3.xyzx
                                                             83 : add r2.w, -r2.w, l(1.000000)
                                                             84 : log r2.w, r2.w
                                                             85 : mul r2.w, r2.w, cb2[6].z
                                                             86 : exp r2.w, r2.w
                                                             87 : mad r1.xyz, v4.xyzx, r0.wwww, -r1.xyzx
                                                             88 : dp3 r0.w, r1.xyzx, r1.xyzx
                                                             89 : rsq r0.w, r0.w
                                                             90 : mul r1.xyz, r0.wwww, r1.xyzx
                                                             91 : dp3 r0.w, cb0[7].xyzx, r1.xyzx
                                                             92 : add r0.w, r0.w, l(1.000000)
                                                             93 : add r1.x, cb2[6].y, l(-1.000000)
                                                             94 : mul r0.w, r0.w, r1.x
                                                             95 : mad r0.w, r0.w, l(0.500000), l(1.000000)
                                                             96 : mul r0.w, r0.w, r2.w
                                                             97 : ge r0.w, r0.w, l(0.100000)
                                                             98 : and r0.w, r0.w, l(0x3f800000)
                                                             99 : dp3 r0.x, r0.xyzx, cb0[7].xyzx
                                                            100 : add r0.x, r0.x, l(1.000000)
                                                            101 : mad r0.x, r0.x, l(0.490000), l(0.010000)
                                                            102 : mov r0.y, l(1.000000)
                                                            103 : sample r3.xyzw, r0.xyxx, t2.xyzw, s2
                                                            104 : max r0.xyz, r3.xyzx, l(0.010000, 0.010000, 0.010000, 0.000000)
                                                            105 : mad r0.xyz, r0.wwww, cb2[9].xyzx, r0.xyzx
                                                            106 : mad r0.xyz, r1.wwww, cb2[10].xyzx, r0.xyzx
                                                            107 : mul r0.xyz, r0.xyzx, r2.xyzx
                                                            108 : max r1.xyz, cb2[7].xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
                                                            109 : mad r0.xyz, cb2[8].xyzx, r0.xyzx, r1.xyzx
                                                            110 : sample r1.xyzw, v3.xyxx, t1.xyzw, s1
                                                            111 : add r2.xy, -r1.zyzz, r1.yzyy
                                                            112 : add_sat r2.xy, -r1.xxxx, r2.xyxx
                                                            113 : add r3.xyz, -cb2[0].xyzx, cb2[1].xyzx
                                                            114 : mad r2.xzw, r2.xxxx, r3.xxyz, cb2[0].xxyz
                                                            115 : add r3.xyz, -r2.xzwx, cb2[2].xyzx
                                                            116 : mad r2.xyz, r2.yyyy, r3.xyzx, r2.xzwx
                                                            117 : mul r1.xyz, r1.yzzy, r1.xyxx
                                                            118 : round_z r1.xyz, r1.xyzx
                                                            119 : add r3.xyz, -r2.xyzx, cb2[3].xyzx
                                                            120 : mad r2.xyz, r1.xxxx, r3.xyzx, r2.xyzx
                                                            121 : add r3.xyz, -r2.xyzx, cb2[4].xyzx
                                                            122 : mad r1.xyw, r1.yyyy, r3.xyxz, r2.xyxz
                                                            123 : add r2.xyz, -r1.xywx, cb2[5].xyzx
                                                            124 : mad r1.xyz, r1.zzzz, r2.xyzx, r1.xywx
                                                            125 : mul o0.xyz, r0.xyzx, r1.xyzx
                                                            126 : mov o0.w, l(1.000000)
                                                            127 : ret
                                                                     // Approximately 0 instruction slots used


                                                                      }


         // Stats for Vertex shader:
         //        d3d11: 21 math
         Pass {
          Name "ShadowCaster"
          Tags { "LIGHTMODE" = "SHADOWCASTER" "QUEUE" = "Geometry+0" "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }
                                                                     //////////////////////////////////
                                                                     //                              //
                                                                     //      Compiled programs       //
                                                                     //                              //
                                                                     //////////////////////////////////
                                                                   //////////////////////////////////////////////////////
                                                                   Global Keywords : <none>
                                                                   Local Keywords : <none>
                                                                   --Hardware tier variant : Tier 1
                                                                   --Vertex shader for "d3d11" :
                                                                     // Stats: 21 math, 2 temp registers
                                                                     Uses vertex data channel "Vertex"
                                                                     Uses vertex data channel "Normal"

                                                                     Constant Buffer "$Globals" (43392 bytes) on slot 0 {
                                                                       Matrix4x4 unity_MatrixVP at 21520
                                                                       Vector4 _ShadowBias at 43328
                                                                       Vector3 _LightDirection at 43376
                                                                     }
                                                                     Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                                                                       Matrix4x4 unity_ObjectToWorld at 0
                                                                       Matrix4x4 unity_WorldToObject at 64
                                                                     }

                                                                     Shader Disassembly :
                                                                     //
                                                                     // Generated by Microsoft (R) D3D Shader Disassembler
                                                                     //
                                                                     //
                                                                     // Input signature:
                                                                     //
                                                                     // Name                 Index   Mask Register SysValue  Format   Used
                                                                     // -------------------- ----- ------ -------- -------- ------- ------
                                                                     // POSITION                 0   xyz         0     NONE   float   xyz 
                                                                     // NORMAL                   0   xyz         1     NONE   float   xyz 
                                                                     // TANGENT                  0   xyzw        2     NONE   float       
                                                                     //
                                                                     //
                                                                     // Output signature:
                                                                     //
                                                                     // Name                 Index   Mask Register SysValue  Format   Used
                                                                     // -------------------- ----- ------ -------- -------- ------- ------
                                                                     // SV_POSITION              0   xyzw        0      POS   float   xyzw
                                                                     //
                                                                           vs_4_0
                                                                           dcl_constantbuffer CB0[2712], immediateIndexed
                                                                           dcl_constantbuffer CB1[7], immediateIndexed
                                                                           dcl_input v0.xyz
                                                                           dcl_input v1.xyz
                                                                           dcl_output_siv o0.xyzw, position
                                                                           dcl_temps 2
                                                                        0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
                                                                        1 : mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
                                                                        2 : mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
                                                                        3 : add r0.xyz, r0.xyzx, cb1[3].xyzx
                                                                        4 : mad r0.xyz, cb0[2711].xyzx, cb0[2708].xxxx, r0.xyzx
                                                                        5 : dp3 r1.x, v1.xyzx, cb1[4].xyzx
                                                                        6 : dp3 r1.y, v1.xyzx, cb1[5].xyzx
                                                                        7 : dp3 r1.z, v1.xyzx, cb1[6].xyzx
                                                                        8 : dp3 r0.w, r1.xyzx, r1.xyzx
                                                                        9 : max r0.w, r0.w, l(0.000000)
                                                                       10 : rsq r0.w, r0.w
                                                                       11 : mul r1.xyz, r0.wwww, r1.xyzx
                                                                       12 : dp3_sat r0.w, cb0[2711].xyzx, r1.xyzx
                                                                       13 : add r0.w, -r0.w, l(1.000000)
                                                                       14 : mul r0.w, r0.w, cb0[2708].y
                                                                       15 : mad r0.xyz, r1.xyzx, r0.wwww, r0.xyzx
                                                                       16 : mul r1.xyzw, r0.yyyy, cb0[1346].xyzw
                                                                       17 : mad r1.xyzw, cb0[1345].xyzw, r0.xxxx, r1.xyzw
                                                                       18 : mad r0.xyzw, cb0[1347].xyzw, r0.zzzz, r1.xyzw
                                                                       19 : add r0.xyzw, r0.xyzw, cb0[1348].xyzw
                                                                       20 : min o0.z, r0.w, r0.z
                                                                       21 : mov o0.xyw, r0.xyxw
                                                                       22 : ret
                                                                               // Approximately 0 instruction slots used


                                                                               -- Hardware tier variant : Tier 1
                                                                               --Fragment shader for "d3d11" :
                                                                               Shader Disassembly :
                                                                           //
                                                                           // Generated by Microsoft (R) D3D Shader Disassembler
                                                                           //
                                                                           //
                                                                           // Input signature:
                                                                           //
                                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                                           // SV_POSITION              0   xyzw        0      POS   float       
                                                                           //
                                                                           //
                                                                           // Output signature:
                                                                           //
                                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                                           // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                                                                           //
                                                                                 ps_4_0
                                                                                 dcl_output o0.xyzw
                                                                              0: mov o0.xyzw, l(0,0,0,0)
                                                                              1 : ret
                                                                                     // Approximately 0 instruction slots used


                                                                                      }


                                                                     // Stats for Vertex shader:
                                                                     //        d3d11: 8 math
                                                                     Pass {
                                                                      Name "DepthOnly"
                                                                      Tags { "LIGHTMODE" = "DepthOnly" "QUEUE" = "Geometry+0" "RenderType" = "Opaque" "RenderPipeline" = "UniversalPipeline" }
                                                                      ZWrite On
                                                                      ColorMask 0
                                                                                     //////////////////////////////////
                                                                                     //                              //
                                                                                     //      Compiled programs       //
                                                                                     //                              //
                                                                                     //////////////////////////////////
                                                                                   //////////////////////////////////////////////////////
                                                                                   Global Keywords : <none>
                                                                                   Local Keywords : <none>
                                                                                   --Hardware tier variant : Tier 1
                                                                                   --Vertex shader for "d3d11" :
                                                                                     // Stats: 8 math, 2 temp registers
                                                                                     Uses vertex data channel "Vertex"

                                                                                     Constant Buffer "$Globals" (43376 bytes) on slot 0 {
                                                                                       Matrix4x4 unity_MatrixVP at 21520
                                                                                     }
                                                                                     Constant Buffer "UnityPerDraw" (384 bytes) on slot 1 {
                                                                                       Matrix4x4 unity_ObjectToWorld at 0
                                                                                     }

                                                                                     Shader Disassembly :
                                                                                     //
                                                                                     // Generated by Microsoft (R) D3D Shader Disassembler
                                                                                     //
                                                                                     //
                                                                                     // Input signature:
                                                                                     //
                                                                                     // Name                 Index   Mask Register SysValue  Format   Used
                                                                                     // -------------------- ----- ------ -------- -------- ------- ------
                                                                                     // POSITION                 0   xyz         0     NONE   float   xyz 
                                                                                     // NORMAL                   0   xyz         1     NONE   float       
                                                                                     // TANGENT                  0   xyzw        2     NONE   float       
                                                                                     //
                                                                                     //
                                                                                     // Output signature:
                                                                                     //
                                                                                     // Name                 Index   Mask Register SysValue  Format   Used
                                                                                     // -------------------- ----- ------ -------- -------- ------- ------
                                                                                     // SV_POSITION              0   xyzw        0      POS   float   xyzw
                                                                                     //
                                                                                           vs_4_0
                                                                                           dcl_constantbuffer CB0[1349], immediateIndexed
                                                                                           dcl_constantbuffer CB1[4], immediateIndexed
                                                                                           dcl_input v0.xyz
                                                                                           dcl_output_siv o0.xyzw, position
                                                                                           dcl_temps 2
                                                                                        0: mul r0.xyz, v0.yyyy, cb1[1].xyzx
                                                                                        1 : mad r0.xyz, cb1[0].xyzx, v0.xxxx, r0.xyzx
                                                                                        2 : mad r0.xyz, cb1[2].xyzx, v0.zzzz, r0.xyzx
                                                                                        3 : add r0.xyz, r0.xyzx, cb1[3].xyzx
                                                                                        4 : mul r1.xyzw, r0.yyyy, cb0[1346].xyzw
                                                                                        5 : mad r1.xyzw, cb0[1345].xyzw, r0.xxxx, r1.xyzw
                                                                                        6 : mad r0.xyzw, cb0[1347].xyzw, r0.zzzz, r1.xyzw
                                                                                        7 : add o0.xyzw, r0.xyzw, cb0[1348].xyzw
                                                                                        8 : ret
                                                                                               // Approximately 0 instruction slots used


                                                                                               -- Hardware tier variant : Tier 1
                                                                                               --Fragment shader for "d3d11" :
                                                                                               Shader Disassembly :
                                                                                           //
                                                                                           // Generated by Microsoft (R) D3D Shader Disassembler
                                                                                           //
                                                                                           //
                                                                                           // Input signature:
                                                                                           //
                                                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                                                           // SV_POSITION              0   xyzw        0      POS   float       
                                                                                           //
                                                                                           //
                                                                                           // Output signature:
                                                                                           //
                                                                                           // Name                 Index   Mask Register SysValue  Format   Used
                                                                                           // -------------------- ----- ------ -------- -------- ------- ------
                                                                                           // SV_TARGET                0   xyzw        0   TARGET   float   xyzw
                                                                                           //
                                                                                                 ps_4_0
                                                                                                 dcl_output o0.xyzw
                                                                                              0: mov o0.xyzw, l(0,0,0,0)
                                                                                              1 : ret
                                                                                                     // Approximately 0 instruction slots used


                                                                                                      }
     }
         Fallback "Hidden/Shader Graph/FallbackError"
}