using UnityEngine;
using System.Collections;

namespace Criatures2021
{
    public enum AttackNameId
    {
        cancelado = -2,
        nulo = -1,
        rajadaDeAgua,
        turboDeAgua,
        bolaDeFogo,
        rajadaDeFogo,
        laminaDeFolha,
        furacaoDeFolhas,
        chifre,
        tapa,
        garra,
        chicoteDeMao,
        dentada,
        bico,
        ventania,
        ventosCortantes,
        gosmaDeInseto,
        gosmaAcida,
        chicoteDeCalda,
        cabecada,
        eletricidade,
        eletricidadeConcentrada,
        agulhaVenenosa,
        ondaVenenosa,
        chute,
        espada,
        sobreSalto,
        cascalho,
        pedregulho,
        rajadaDeTerra,
        energiaDeGarras,
        vingancaDaTerra,
        psicose,
        hidroBomba,
        bolaPsiquica,
        tosteAtaque,
        tempestadeDeFolhas,
        chuvaVenenosa,
        multiplicar,
        tempestadeEletrica,
        avalanche,
        anelDoOlhar,
        olharMal,
        cortinaDeTerra,
        teletransporte,
        sobreVoo,
        olharEnfraquecedor,
        bombaDeGas,
        rajadaDeGas,
        cortinaDeFumaca,
        bastao,
        sabreDeAsa,
        sabreDeBastao,
        sabreDeNadadeira,
        sabreDeEspada,
        tesoura,
        ataqueEmGiro
    }
}